// <auto-generated />
using System;
using EFCoreProject2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreProject2.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20260726122808_addTabels")]
    partial class addTabels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreProject2.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentNumber")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ManageStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DepartmentID");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("departments");
                });

            modelBuilder.Entity("EFCoreProject2.Models.Dependent", b =>
                {
                    b.Property<int>("DependentID")
                        .HasColumnType("int");

                    b.Property<string>("DependentName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("relationsship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DependentID", "DependentName");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("dependents");
                });

            modelBuilder.Entity("EFCoreProject2.Models.DeptLocation", b =>
                {
                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentLocation")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DepartmentID", "DepartmentLocation");

                    b.ToTable("DeptLocations");
                });

            modelBuilder.Entity("EFCoreProject2.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeAge")
                        .HasColumnType("int");

                    b.Property<double>("EmployeeSalary")
                        .HasColumnType("float");

                    b.Property<int>("EmployeeSsn")
                        .HasColumnType("int");

                    b.Property<int>("supervisorId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("supervisorId");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("EFCoreProject2.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("ProjectLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("EFCoreProject2.Models.empProj", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("empProjs");
                });

            modelBuilder.Entity("EmployeeProject", b =>
                {
                    b.Property<int>("EmployeesEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("projectsProjectId")
                        .HasColumnType("int");

                    b.HasKey("EmployeesEmployeeId", "projectsProjectId");

                    b.HasIndex("projectsProjectId");

                    b.ToTable("EmployeeProject");
                });

            modelBuilder.Entity("EFCoreProject2.Models.Department", b =>
                {
                    b.HasOne("EFCoreProject2.Models.Employee", "Employee")
                        .WithOne("ManageDepart")
                        .HasForeignKey("EFCoreProject2.Models.Department", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EFCoreProject2.Models.Dependent", b =>
                {
                    b.HasOne("EFCoreProject2.Models.Employee", "emp")
                        .WithOne("Dependent")
                        .HasForeignKey("EFCoreProject2.Models.Dependent", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("emp");
                });

            modelBuilder.Entity("EFCoreProject2.Models.DeptLocation", b =>
                {
                    b.HasOne("EFCoreProject2.Models.Department", "Dept")
                        .WithMany()
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dept");
                });

            modelBuilder.Entity("EFCoreProject2.Models.Employee", b =>
                {
                    b.HasOne("EFCoreProject2.Models.Department", "D")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreProject2.Models.Employee", "supervisor")
                        .WithMany("supervisee")
                        .HasForeignKey("supervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("D");

                    b.Navigation("supervisor");
                });

            modelBuilder.Entity("EFCoreProject2.Models.empProj", b =>
                {
                    b.HasOne("EFCoreProject2.Models.Employee", "emp")
                        .WithMany("empProjs")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreProject2.Models.Project", "proj")
                        .WithMany("empProjs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("emp");

                    b.Navigation("proj");
                });

            modelBuilder.Entity("EmployeeProject", b =>
                {
                    b.HasOne("EFCoreProject2.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreProject2.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("projectsProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFCoreProject2.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("EFCoreProject2.Models.Employee", b =>
                {
                    b.Navigation("Dependent")
                        .IsRequired();

                    b.Navigation("ManageDepart")
                        .IsRequired();

                    b.Navigation("empProjs");

                    b.Navigation("supervisee");
                });

            modelBuilder.Entity("EFCoreProject2.Models.Project", b =>
                {
                    b.Navigation("empProjs");
                });
#pragma warning restore 612, 618
        }
    }
}
